use diesel::prelude::*;

// Import the schema generated by Diesel
use crate::schema::*;

// Admin models - Queryable structs (for reading from database)
#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = admins)]
pub struct Admin {
    pub id: String,
    pub username: String,
    pub password_hash: String,
    pub is_active: bool,
    pub created_at: chrono::NaiveDateTime,
    pub updated_at: chrono::NaiveDateTime,
    pub last_login: Option<chrono::NaiveDateTime>,
}

// Admin models - Insertable structs (for creating new records)
#[derive(Insertable, Debug)]
#[diesel(table_name = admins)]
pub struct NewAdmin {
    pub id: String,
    pub username: String,
    pub password_hash: String,
    pub is_active: bool,
}